apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
- ingress.yaml
images:
- digest: sha256:d68c49c17120e887908781318d9ff022316c371134d378a2027d6e9990802a29
  name: ghcr.io/pushkal-vashishtha/secureshop-api
  newName: ghcr.io/pushkal-vashishtha/secureshop-api
- digest: sha256:99cd8e6c89372cbcd34ead85fbde45f9a584ec03cfa8bf43a165f405b8c91fee
  name: ghcr.io/pushkal-vashishtha/secureshop-web
  newName: ghcr.io/pushkal-vashishtha/secureshop-web
patches:
  - target:
      kind: Deployment
      name: web
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/image
        value: ghcr.io/pushkal-vashishtha/secureshop-web:latest
