apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
images:
  - name: ghcr.io/pushkal-vashishtha/secureshop-api
    digest: sha256:6a2d220e73ddced26b142ff8445628357646c766a46b96a8aa3a5978b6cfb40a
  - name: ghcr.io/pushkal-vashishtha/secureshop-web
    digest: sha256:67bf224ee3dea8c51061a9b70dafc86fdc5dafdec08971424b0515f3d6374fe3
